name: generate snake

on:
  # rebuild once a day
  schedule:
    - cron: "0 */24 * * *"
  # manual run
  workflow_dispatch:
  # rebuild on pushes to main
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # generate snake
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk@v3.3.0
        with:
          github_user_name: bberryw31
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            
      # publish generated files
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
